/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cybsp.h"
#include "cyhal.h"
#include "cy_retarget_io.h"
#include <inttypes.h>

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: HandleError
 * Summary:
 *  User defined error handling function.
 * Parameters:
 *  status - status for evaluation.
 * Return:
 *  none
 **********************************************************************************************************************
 */
void HandleError(cy_rslt_t status)
{
    if (CY_RSLT_SUCCESS != status)
    {
        /* Halt the CPU while debugging */
        CY_ASSERT(0);
    }
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function for the CPU. It configures the PWM and puts the CPU
 *  in Sleep mode to save power.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    /* API return code */
    cy_rslt_t result;

#if defined(CY_DEVICE_SECURE)
    cyhal_wdt_t wdtObj;
    /* Clear watchdog timer so that it doesn't trigger a reset */
    result = cyhal_wdt_init(&wdtObj, cyhal_wdt_get_max_timeout_ms());
    CY_ASSERT(CY_RSLT_SUCCESS == result);
    cyhal_wdt_free(&wdtObj);
#endif

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    HandleError(result);

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize the retarget-io to use the debug UART port */
    result = cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX,
                                 CY_RETARGET_IO_BAUDRATE);
    HandleError(result);

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");
    printf("****************** "
           "PWM square wave simultaneous sw trigger"
           "****************** \r\n\n");

    /* TCPWM configuration to use group trigger #0 as its starting trigger */
    PWM_LEDA_config.startInputMode = CY_TCPWM_INPUT_RISINGEDGE;
    PWM_LEDA_config.startInput = 2 + TCPWM1_TR_ONE_CNT_NR;
    PWM_LEDB_config.startInputMode = CY_TCPWM_INPUT_RISINGEDGE;
    PWM_LEDB_config.startInput = 2 + TCPWM1_TR_ONE_CNT_NR;

    /* Initialize the TCPWM block */
    Cy_TCPWM_PWM_Init(PWM_LEDA_HW, PWM_LEDA_NUM, &PWM_LEDA_config);
    Cy_TCPWM_PWM_Init(PWM_LEDB_HW, PWM_LEDB_NUM, &PWM_LEDB_config);

    /* Enable the TCPWM block */
    Cy_TCPWM_PWM_Enable(PWM_LEDA_HW, PWM_LEDA_NUM);
    Cy_TCPWM_PWM_Enable(PWM_LEDB_HW, PWM_LEDB_NUM);

    /* Start the TCPWM block simultaneously */
    Cy_TrigMux_SwTrigger(TRIG_OUT_MUX_5_TCPWM1_ALL_CNT_TR_IN0, CY_TRIGGER_TWO_CYCLES);

    printf("PWM started successfully...\r\n");

    for (;;)
    {
        /* Put the CPU into sleep mode to save power */
        printf("Entering the sleep mode...\r\n");
        cyhal_syspm_sleep();
    }
}

/* [] END OF FILE */
